import base64
import http.cookiejar
import io
import logging
import os
import re
import tempfile
import time

logger = logging.getLogger("jodify.cookie_manager")

_cached_cookie_path: str | None = None
_cached_cookie_hash: str | None = None
_last_check_time: float = 0.0


def sanitize_netscape_cookies(raw_text: str) -> str | None:
    """
    Convierte cualquier formato de texto de cookies (con espacios, sin encabezados,
    con comillas de variables de entorno, o con caracteres de salto de línea desordenados)
    en un archivo de cookies Netscape 100% válido y compatible con MozillaCookieJar y yt-dlp.
    """
    if not raw_text:
        return None

    raw_text = raw_text.strip()
    if not raw_text:
        return None

    # Eliminar comillas envolventes comunes de variables de entorno de Render/Docker/.env
    if (raw_text.startswith('"') and raw_text.endswith('"')) or (raw_text.startswith("'") and raw_text.endswith("'")):
        raw_text = raw_text[1:-1].strip()

    # Si viene en Base64, decodificar
    if not raw_text.startswith("#") and "\n" not in raw_text and len(raw_text) > 40:
        try:
            decoded = base64.b64decode(raw_text).decode("utf-8", errors="ignore")
            if "# Netscape" in decoded or ".youtube.com" in decoded or ".google.com" in decoded:
                raw_text = decoded
        except Exception:
            pass

    # Normalizar saltos de línea
    raw_text = raw_text.replace("\r\n", "\n").replace("\r", "\n")
    lines = raw_text.split("\n")

    valid_cookie_lines: list[str] = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        # Ignorar encabezados viejos o comentarios que no sean #HttpOnly_
        if stripped.startswith("# Netscape") or stripped.startswith("# HTTP Cookie File"):
            continue
        if stripped.startswith("#") and not stripped.startswith("#HttpOnly_"):
            continue

        prefix = ""
        cookie_data = stripped
        if cookie_data.startswith("#HttpOnly_"):
            prefix = "#HttpOnly_"
            cookie_data = cookie_data[len("#HttpOnly_"):].strip()

        # Separar por tabulaciones o por múltiples espacios en blanco
        if "\t" in cookie_data:
            parts = [p.strip() for p in cookie_data.split("\t")]
        else:
            parts = [p.strip() for p in re.split(r"\s+", cookie_data)]

        # Un archivo Netscape requiere exactamente 7 campos:
        # domain \t include_subdomains \t path \t secure \t expiry \t name \t value
        if len(parts) >= 7:
            domain = parts[0]
            subdomains = parts[1].upper() if parts[1].upper() in ("TRUE", "FALSE") else ("TRUE" if domain.startswith(".") else "FALSE")
            path = parts[2]
            secure = parts[3].upper() if parts[3].upper() in ("TRUE", "FALSE") else "TRUE"
            expires = parts[4]
            name = parts[5]
            value = parts[6] if len(parts) == 7 else " ".join(parts[6:])
            valid_cookie_lines.append(f"{prefix}{domain}\t{subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}")

    if not valid_cookie_lines:
        return None

    cleaned = "# Netscape HTTP Cookie File\n# This file is generated by JodiFy\n\n" + "\n".join(valid_cookie_lines) + "\n"

    # Validar estrictamente con MozillaCookieJar antes de darlo por bueno
    try:
        jar = http.cookiejar.MozillaCookieJar()
        jar._really_load(io.StringIO(cleaned), "cookies_validation.txt", False, False)
        return cleaned
    except Exception as exc:
        logger.warning(f"[CookieManager] Las cookies no pasaron la validación de MozillaCookieJar: {exc}")
        return None


def get_valid_cookies_file() -> str | None:
    """
    Busca, valida y prepara de forma segura la ruta de cookies para yt-dlp.
    Garantiza que yt-dlp NUNCA reciba un archivo corrupto que provoque:
    'does not look like a Netscape format cookies file'.
    """
    global _cached_cookie_path, _cached_cookie_hash, _last_check_time

    now = time.time()
    # Reutilizar resultado cacheado por 60 segundos a menos que cambie el valor
    if _cached_cookie_path and (now - _last_check_time < 60.0):
        if os.path.exists(_cached_cookie_path):
            return _cached_cookie_path

    _last_check_time = now

    candidate_files = [
        os.environ.get("YOUTUBE_COOKIES_PATH"),
        os.environ.get("COOKIES_FILE"),
        "/etc/secrets/cookies.txt",
        "/etc/secrets/youtube_cookies.txt",
        os.path.join(os.getcwd(), "cookies.txt"),
    ]

    # 1. Comprobar archivos físicos
    for filepath in candidate_files:
        if filepath and os.path.exists(filepath):
            try:
                # Comprobar si ya es válido
                jar = http.cookiejar.MozillaCookieJar(filepath)
                jar.load(ignore_discard=True, ignore_expires=True)
                _cached_cookie_path = filepath
                return filepath
            except Exception:
                # Si existe pero le faltan tabs o formato, intentar sanitizarlo
                try:
                    with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                        file_content = f.read()
                    sanitized = sanitize_netscape_cookies(file_content)
                    if sanitized:
                        tmp_path = os.path.join(tempfile.gettempdir(), "jodify_yt_cookies.txt")
                        with open(tmp_path, "w", encoding="utf-8") as out:
                            out.write(sanitized)
                        _cached_cookie_path = tmp_path
                        return tmp_path
                except Exception as e:
                    logger.warning(f"[CookieManager] Error leyendo archivo de cookies {filepath}: {e}")

    # 2. Comprobar texto en variables de entorno (Render, Railway, Docker, .env)
    cookie_text = os.environ.get("YOUTUBE_COOKIES_TEXT") or os.environ.get("YOUTUBE_COOKIES")
    if cookie_text:
        text_hash = str(hash(cookie_text))
        if _cached_cookie_path and _cached_cookie_hash == text_hash and os.path.exists(_cached_cookie_path):
            return _cached_cookie_path

        sanitized = sanitize_netscape_cookies(cookie_text)
        if sanitized:
            try:
                tmp_path = os.path.join(tempfile.gettempdir(), "jodify_yt_cookies.txt")
                with open(tmp_path, "w", encoding="utf-8") as out:
                    out.write(sanitized)
                _cached_cookie_path = tmp_path
                _cached_cookie_hash = text_hash
                logger.info("[CookieManager] Archivo Netscape de YouTube generado y validado con éxito.")
                return tmp_path
            except Exception as e:
                logger.warning(f"[CookieManager] Error guardando cookies sanitizadas temporales: {e}")
        else:
            logger.warning("[CookieManager] YOUTUBE_COOKIES_TEXT presente pero no se pudieron extraer cookies válidas.")

    _cached_cookie_path = None
    return None
